export const DEFAULT_TEMPLATES = [
  {
    name: "H-1B specialty occupation (admin collection)",
    caseType: "H-1B",
    reminderDefaults: { cadenceDays: 3, pauseOnSubmit: true },
    items: [
      {
        title: "Passport biographic page",
        required: true,
        instructions: "Upload a color scan of the passport identity page.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 7,
        expectedSchema: ["full_name", "date_of_birth", "passport_number"],
      },
      {
        title: "Most recent I-94",
        required: true,
        instructions: "Upload the I-94 travel history printout if available.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 7,
        expectedSchema: ["full_name"],
      },
      {
        title: "Resume / CV",
        required: true,
        instructions: "Current resume with education and employment history.",
        allowedTypes: "pdf,docx",
        dueOffsetDays: 10,
        expectedSchema: ["full_name"],
      },
      {
        title: "Highest diploma or degree",
        required: true,
        instructions: "Diploma or degree certificate. Translations can be uploaded as a later version.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 14,
        expectedSchema: ["full_name"],
      },
      {
        title: "Employment / offer letter",
        required: true,
        instructions: "Letter on company letterhead describing role and start date.",
        allowedTypes: "pdf",
        dueOffsetDays: 10,
        expectedSchema: ["employer", "employee_name"],
      },
      {
        title: "Prior approval notices (if any)",
        required: false,
        instructions: "Optional I-797 notices from prior petitions.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 14,
        expectedSchema: [],
      },
    ],
    questions: [
      { prompt: "Full legal name", fieldKey: "legal_name", required: true, inputType: "text" },
      { prompt: "Date of birth", fieldKey: "dob", required: true, inputType: "date" },
      { prompt: "Country of citizenship", fieldKey: "citizenship", required: true, inputType: "text" },
      { prompt: "Current US status (if any)", fieldKey: "us_status", required: false, inputType: "text" },
      { prompt: "Job title", fieldKey: "job_title", required: true, inputType: "text" },
      { prompt: "Employer / petitioner name", fieldKey: "employer", required: true, inputType: "text" },
    ],
  },
  {
    name: "Family petition I-130 (admin collection)",
    caseType: "I-130",
    reminderDefaults: { cadenceDays: 4, pauseOnSubmit: true },
    items: [
      {
        title: "Petitioner passport or ID",
        required: true,
        instructions: "Government photo ID for the petitioner.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 10,
        expectedSchema: ["full_name"],
      },
      {
        title: "Beneficiary passport",
        required: true,
        instructions: "Passport biographic page for the beneficiary.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 10,
        expectedSchema: ["full_name", "passport_number"],
      },
      {
        title: "Marriage certificate (if applicable)",
        required: false,
        instructions: "Civil marriage certificate if filing based on marriage.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 14,
        expectedSchema: ["full_name"],
      },
      {
        title: "Proof of relationship evidence",
        required: true,
        instructions: "Photos, joint records, or other relationship evidence as requested by counsel.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 21,
        expectedSchema: [],
      },
    ],
    questions: [
      { prompt: "Petitioner full name", fieldKey: "petitioner_name", required: true, inputType: "text" },
      { prompt: "Beneficiary full name", fieldKey: "beneficiary_name", required: true, inputType: "text" },
      { prompt: "Relationship to beneficiary", fieldKey: "relationship", required: true, inputType: "text" },
    ],
  },
  {
    name: "Naturalization N-400 (admin collection)",
    caseType: "N-400",
    reminderDefaults: { cadenceDays: 5, pauseOnSubmit: true },
    items: [
      {
        title: "Permanent resident card",
        required: true,
        instructions: "Front and back of the green card.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 7,
        expectedSchema: ["full_name"],
      },
      {
        title: "Passport biographic page",
        required: true,
        instructions: "Current passport identity page.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 7,
        expectedSchema: ["full_name", "passport_number"],
      },
      {
        title: "Selective service proof (if applicable)",
        required: false,
        instructions: "Upload only if counsel requested it.",
        allowedTypes: "pdf,jpg,png",
        dueOffsetDays: 21,
        expectedSchema: [],
      },
    ],
    questions: [
      { prompt: "Full legal name", fieldKey: "legal_name", required: true, inputType: "text" },
      { prompt: "A-number", fieldKey: "a_number", required: true, inputType: "text" },
      { prompt: "Date became permanent resident", fieldKey: "lpr_date", required: true, inputType: "date" },
    ],
  },
];
